name: Debug PR Body

on:
  pull_request:
    types: [opened, edited]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Body
        run: echo "${{ github.event.pull_request.body }}"
