name: Label Issue on PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approval
        id: check_approval
        run: |
          echo "Review State: ${{ github.event.review.state }}"
          if [[ "${{ github.event.review.state }}" == "approved" ]]; then
            echo "approved=true" >> $GITHUB_ENV
          else
            echo "approved=false" >> $GITHUB_ENV
          fi

      - name: Print PR Body
        run: echo "${{ github.event.pull_request.body }}"

      - name: Add label to linked issue
        if: env.approved == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            console.log(`PR Body: ${pr.body}`);
            const linkedIssues = pr.body.match(/#(\d+)/g) || [];
            console.log(`Found linked issues: ${linkedIssues}`);

            if (linkedIssues.length > 0) {
              for (const issue of linkedIssues) {
                const issueNumber = issue.replace('#', '');
                console.log(`Attempting to add label to issue #${issueNumber}`);

                try {
                  const response = await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: parseInt(issueNumber),
                    labels: ['approved']  // Replace with your actual label
                  });
                  console.log(`Label added to issue #${issueNumber}:`, response.data);
                } catch (error) {
                  console.error(`Failed to add label to issue #${issueNumber}: ${error.message}`);
                }
              }
            } else {
              console.log('No linked issues found in PR body.');
            }
