name: Label Issue after PR closing

on:
  pull_request:
    types: [closed]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:

      - name: Print PR Body
        run: echo "${{ github.event.pull_request.body }}"

      - name: Remove label on linked issue if PR closed and not merged
        uses: actions/github-script@v6
        if: github.event.pull_request.merged == false
        with:
          script: |
            const pr = context.payload.pull_request;
            const myLabel = 'status: has pull request';
            console.log(`PR Body: ${pr.body}`);
            const linkedIssues = pr.body.match(/(fixe?s?||close?s?|resolves?|addresse?s?)\s+#(\d+)/gi) || [];

            if (linkedIssues.length > 0) {
              for (const issue of linkedIssues) {
                // Extract just the number part (the digits after the # symbol)
                const issueNumber = issue.match(/#(\d+)/)[1];  // Extract the digits after '#'
                console.log(`Issue #${issueNumber}`);
            
                try {
                    const { data } = await github.rest.issues.listLabelsOnIssue({
                    issue_number: issueNumber,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                  })

                  // Return early if there are no labels
                  if (data.length == 0){
                    console.log(`Issue ${issueNumber} has no labels; not attempting to remove label ${myLabel}`)
                    return
                  }

            // Check if myLabel is present
            const filteredData = data.filter(label => label.name == myLabel)

            // Return early if filtering didn't identify the label as present
            if (filteredData.length == 0){
              console.log(`Label "${myLabel}" not found on issue; not attempting to remove it.`)
              return
            }

            console.log(`Label "${myLabel}" found! Now deleting it from the issue...`)

            await github.rest.issues.removeLabel({
              issue_number: context.{issueNumber},
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: myLabel
            })
            }
            } else {
              console.log('No linked issues found in PR body.');
            }
